import { readFile, writeFile } from "node:fs/promises";
import peggy from "peggy";

const grammarPath = new URL("../src/dsl/grammar.pegjs", import.meta.url);
const outputPath = new URL("../src/dsl/parser.generated.ts", import.meta.url);

const grammar = await readFile(grammarPath, "utf8");
const source = peggy.generate(grammar, {
  format: "es",
  output: "source",
  grammarSource: "dsl.pegjs",
});

const header = `// @ts-nocheck
// Generated by scripts/generateDslParser.mjs. Do not edit directly.

`;

await writeFile(outputPath, header + source, "utf8");
